'use client';
import {useState} from 'react';
import {probabilityOfExposure,type AnnualExposure} from '@/lib/hazard-events';
import type {ExposureResponse} from '@/lib/hazard-exports';
export function ExposureCharts({results,requested}:{results:ExposureResponse[];requested:number}){
 const [selectedYear,setSelectedYear]=useState('');if(!results.length)return null;
 const annual=results.map(r=>r.annual),summary=probabilityOfExposure(annual),spec=results[0].effective_spec;
 const selected=results.find(r=>String(r.annual.year)===selectedYear)??results[0],samples=selected.annual.samples;
 const values=samples.flatMap(s=>[s.value,s.secondary_value].filter((v):v is number=>typeof v==='number'&&Number.isFinite(v)));
 const lo=Math.min(spec.threshold,...values),hi=Math.max(spec.threshold,spec.secondary_threshold??spec.threshold,...values),span=hi-lo||1;
 const x=(i:number)=>55+850*i/Math.max(1,samples.length-1),y=(v:number)=>235-190*(v-lo)/span;
 function path(secondary=false){let pen=false;return samples.map((s,i)=>{const v=secondary?s.secondary_value:s.value;if(v==null){pen=false;return '';}const p=(pen?'L':'M')+x(i).toFixed(2)+','+y(v).toFixed(2);pen=true;return p;}).join(' ');}
 const unit=spec.resolution==='hour'?'hours':spec.profile?.includes('night')?'nights':'days';
 const maximum=Math.max(spec.min_samples,...annual.map(a=>a.longest_run??0),1);
 const durations=[...new Set([1,2,3,5,7,10,14,18,24,30,spec.min_samples])].sort((a,b)=>a-b);
 return <section className="space-y-5 rounded border border-line bg-bg-panel/50 p-5">
  <div className="flex flex-wrap gap-8"><div><p className="text-xs uppercase tracking-wide text-ink-mute">Historical exposure frequency</p><p className="mt-2 text-4xl font-semibold text-[#B9FF3B]">{summary.probability===null?'No valid years':(summary.probability*100).toFixed(1)+'%'}</p><p className="mt-1 text-xs text-ink-dim">{summary.event_years} event years / {summary.valid_years} valid years · {results.length}/{requested} successful queries</p></div><div className="max-w-xl text-xs leading-relaxed text-ink-dim"><p>Event: {spec.operator} {spec.threshold} {spec.unit}{spec.secondary_threshold!==undefined?' and nighttime mean >= '+spec.secondary_threshold+' C':''} for at least {spec.min_samples} {spec.mode==='accumulated'?'accumulated':'consecutive'} {unit}.</p><p className="mt-2">Frequency refers to this selected crop cell and phase. Missing years are excluded. A treatment duration is not the maximum a plant can tolerate, and exposure frequency is not damage probability.</p></div></div>
  <label className="flex flex-wrap items-center gap-3 text-sm text-ink">Time series — planting year<select aria-label="Time-series year" className="rounded border border-line bg-bg-panel p-2" value={selected.annual.year} onChange={e=>setSelectedYear(e.target.value)}>{results.map(r=><option key={r.annual.year}>{r.annual.year}</option>)}</select></label>
  <div className="overflow-x-auto"><svg viewBox="0 0 950 285" role="img" aria-label="Climate time series with threshold and qualifying event samples; gaps indicate missing values" className="min-w-[600px] w-full"><rect x="55" y="30" width="850" height="205" fill="rgba(255,255,255,.025)"/>{[0,.5,1].map(f=><g key={f}><line x1="55" x2="905" y1={y(lo+span*f)} y2={y(lo+span*f)} stroke="#ffffff18"/><text x="48" y={y(lo+span*f)+4} textAnchor="end" fill="#9FB7C5" fontSize="11">{(lo+span*f).toFixed(1)}</text></g>)}<line x1="55" x2="905" y1={y(spec.threshold)} y2={y(spec.threshold)} stroke="#F5B74F" strokeDasharray="6 5"/><path d={path()} fill="none" stroke="#7FD4DF" strokeWidth="1.8"/>{spec.secondary_threshold!==undefined&&<><line x1="55" x2="905" y1={y(spec.secondary_threshold)} y2={y(spec.secondary_threshold)} stroke="#C3A5FF" strokeDasharray="4 4"/><path d={path(true)} fill="none" stroke="#C3A5FF" strokeWidth="1.6"/></>}{samples.map((s,i)=>s.in_qualifying_event&&s.value!==null?<circle key={i} cx={x(i)} cy={y(s.value)} r="2" fill="#B9FF3B"/>:null)}<text x="55" y="258" fill="#9FB7C5" fontSize="11">{selected.annual.start.slice(0,16)} UTC</text><text x="905" y="258" textAnchor="end" fill="#9FB7C5" fontSize="11">{selected.annual.end_exclusive.slice(0,16)} UTC (exclusive)</text><text x="55" y="18" fill="#9FB7C5" fontSize="11">{spec.unit} · cyan: primary variable · green: qualifying event{spec.secondary_threshold!==undefined?' · purple: nighttime variable':''}</text></svg></div>
  {spec.mode==='rolling_mean'&&<p className="text-xs text-ink-dim">The line shows daily maxima. Event membership is determined by complete six-day rolling means, not individual crossings of the dashed threshold.</p>}
  <div className="grid gap-6 lg:grid-cols-2"><div><h3 className="mb-3 text-sm text-ink">Longest consecutive exposure by year ({unit})</h3><div className="max-h-72 space-y-2 overflow-y-auto">{annual.map(a=><div key={a.year} className="flex items-center gap-2 text-xs text-ink-dim"><span className="w-10">{a.year}</span><div className="h-3 flex-1 bg-white/5"><div className="h-3" style={{width:100*(a.longest_run??0)/maximum+'%',background:a.event_occurred?'#B9FF3B':'#76B7C5'}}/></div><span className="w-20 text-right">{a.longest_run??'Missing'}</span></div>)}</div></div><div><h3 className="mb-3 text-sm text-ink">Duration sensitivity: P({spec.mode==='accumulated'?'accumulated exposure':'longest exposure'} ≥ d)</h3><p className="mb-3 text-xs text-ink-mute">Each point uses complete years long enough to evaluate that duration. This is not a plant-survival curve.</p><div className="flex h-44 items-end gap-2 border-b border-line">{durations.map(d=>{const valid=annual.filter(a=>a.complete&&a.expected_samples>=Math.max(d,spec.window_samples??1));const p=valid.length?valid.filter(a=>(spec.mode==='accumulated'?(a.exposure_samples??0):(a.observed_longest_run??a.longest_run??0))>=d).length/valid.length:null;return <div key={d} className="flex h-full min-w-0 flex-1 flex-col justify-end text-center text-[9px] text-ink-dim"><span>{p===null?'n/a':Math.round(p*100)+'%'}</span><div title={d+' '+unit+'; '+valid.length+' valid years'} className="mt-1 min-h-[1px] bg-cool/70" style={{height:(p??0)*110}}/><span className="mt-1">{d}</span></div>;})}</div><p className="mt-2 text-xs text-ink-mute">d ({unit})</p></div></div>
  <details className="text-xs text-ink-dim"><summary className="cursor-pointer text-cool">Annual coverage and exposure intervals</summary><div className="mt-3 overflow-x-auto"><table className="w-full text-left"><thead><tr><th className="p-2">Year</th><th>Samples</th><th>Event</th><th>Start → exclusive end (UTC)</th></tr></thead><tbody>{annual.map(a=><tr key={a.year} className="border-t border-line"><td className="p-2">{a.year}</td><td>{a.available_samples}/{a.expected_samples}</td><td>{a.event_occurred===null?'Not evaluable':a.event_occurred?'Yes':'No'}</td><td>{a.events.map(e=>e.start+' → '+e.end_exclusive+' ('+e.duration+' '+unit+')').join('; ')||'—'}</td></tr>)}</tbody></table></div></details>
 </section>;
}
