'use client';
import {useState} from 'react';
import {pixelWindows,referenceDate} from '@/lib/pixel-phenology';
import {RegionalSelector,type RegionSelection} from './regional-selector';
const colors=['#7FD4DF','#76B7C5','#7FAF7B','#A7C957','#D7B45A','#D98B57'];
export function PhenologyCalendar(){
 const [region,setRegion]=useState<RegionSelection|null>(null);
 const key=region?.zone.representative,[lat,lon]=(key??'0,0').split(',').map(Number);
 const windows=region?pixelWindows(region.data,lat,lon):[],cycle=region?.data.pixels[key??'']?.[1];
 return <div className="mt-6 rounded-sm border border-line glass">
  <div className="border-b border-line p-4"><RegionalSelector onChange={setRegion}/></div>
  {region&&<><div className="space-y-2 border-b border-line p-4 text-[12px] leading-relaxed text-ink-dim"><p><strong className="text-ink">{region.bandLabel} · {region.zone.label}</strong> · {region.zone.count} cells in the crop inventory.</p><p>The six-phase sequence below represents a real archived calendar near this zone’s median planting date and cycle length. It is not an average of disconnected monthly fragments. Latitude alone does not determine crop timing: select a longitude zone and planting regime.</p><p>Representative cycle: {cycle} days. Cycles across this group: {region.zone.cycle_range.join('–')} days. Weather and phenology still vary within the group; calculations use each screened cell’s own calendar.</p></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="text-ink-mute"><tr><th className="p-3">Phase / original stages</th><th className="p-3">Reference dates</th><th className="p-3">Days</th><th className="w-[35%] p-3">One continuous cycle · {cycle} days</th></tr></thead><tbody>{windows.map(w=><tr key={w.phase_code} className="border-t border-line/50"><td className="p-3"><span className="font-medium text-cool">{w.phase_code} — {w.phase_label}</span><span className="mt-1 block max-w-sm text-[10px] text-ink-mute">{w.original_stages.join('; ')}</span></td><td className="whitespace-nowrap p-3 text-ink-dim">{referenceDate(2001,w.start_doy).toISOString().slice(5,10)} Y{w.start_year_offset} → {referenceDate(2001,w.end_doy).toISOString().slice(5,10)} Y{w.end_year_offset}</td><td className="p-3 text-ink">{w.duration_days}</td><td className="p-3"><div className="relative h-7 bg-white/5" aria-label={w.phase_code+' continuous duration '+w.duration_days+' days'}><div className="absolute h-7 rounded-sm" style={{left:100*w.start_offset/cycle!+'%',width:100*w.duration_days/cycle!+'%',backgroundColor:colors[w.phase_order-1]}}/></div></td></tr>)}</tbody></table></div>
  <details className="border-t border-line p-4 text-xs text-ink-dim"><summary className="cursor-pointer text-cool">Evidence, estimates and correspondence revisions</summary><div className="mt-3 space-y-2"><p>All intermediate boundaries are inherited estimates from normalized technical-stage fractions. They are not annually observed dates. Original dates and total cycle length are conserved. Six labels form an operational partition; biological processes can overlap.</p><p>Maize: R1 → FLO; R2 early kernel development → REP; R3–R5 → FIL. Rice: panicle initiation in BBCH 30–39 → REP before flowering. Soybean: R5 through the archived R6–R7 block → FIL; the terminal R8 block → MAT. The precise R7 transition remains unresolved within the original aggregate; its terminal boundary is an estimate.</p><p>Reference coordinate for reproducibility: {key}. Crop-inventory presence is not proof that every farm planted this crop in every queried year.</p><p><a className="text-cool underline" href="https://zenodo.org/records/5062513" target="_blank" rel="noreferrer">GGCMI planting/maturity source</a> · <a className="text-cool underline" href="https://github.com/Pruizf0310/tesis-cereal-climate/blob/main/docs/regional_workflow_v4.md" target="_blank" rel="noreferrer">Scientific correspondence, source Excel files and change history</a></p></div></details></>}
 </div>;
}
