import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),file=path.join(root,'web-v2/public/data/gee_rule_audit.json');
const audit=JSON.parse(fs.readFileSync(file)),daily='ECMWF/ERA5_LAND/DAILY_AGGR',hourly='ECMWF/ERA5_LAND/HOURLY';
const definitions={};
function define(id,variable,equation,threshold,operator,duration,options={}){
 const resolution=options.resolution??'day',profile=options.profile;
 definitions[id]={variable,equation,access:options.access??'gee',equivalence:options.equivalence??'Operational transfer of reviewed exposure',duration_basis:options.duration_basis??'Reviewed exposure duration; not maximum plant tolerance',
  note:options.note??'Meteorological exposure frequency; experimental transfer is not calibrated crop damage probability.',
  spec:{dataset:options.access==='import'?'User-supplied measured or independently modelled series':(resolution==='hour'||profile?hourly:daily),band:options.band??'temperature_2m',resolution,operator,threshold,min_samples:duration,unit:options.unit??'C',mode:options.mode??'run',conversion:options.conversion??'kelvin_to_celsius',interpretation:equation,profile,secondary_threshold:options.secondary_threshold,day_hours:options.day_hours??12,night_start:options.night_start??18},
  csv_variable:options.csv_variable??options.band??'temperature_2m',evidence_update:options.evidence_update??null};
}
const unspecified='Project analysis duration defaults to one sample because the reviewed paper does not establish a duration-specific breakpoint. Change duration for sensitivity analysis; it is not plant tolerance.';
define('MAIZE_EMERGENCE_COLD6','Hourly 2 m air temperature','Tair = ERA5 hourly temperature_2m - 273.15; Tair < 6 C for >=2 consecutive hourly samples.',6,'<',2,{resolution:'hour',note:'The source describes a programmed growth-chamber air-temperature cycle. Field 2 m air temperature is an explicit transfer from that treatment, not soil temperature.',evidence_update:'PLOS ONE 10.1371/journal.pone.0340773, Materials and methods: temperature simulation protocol.'});
define('MAIZE_TASSEL_HEAT38_30_15D','Paired daytime and nighttime mean air temperature','Tday = mean of 06:00–18:00; Tnight = mean of 18:00–06:00. Both >=38/30 C on each of 15 consecutive cycles.',38,'>=',15,{profile:'paired_mean',secondary_threshold:30,note:'Fixed 12/12-hour solar-clock cycle is the project field equivalent of the paired experimental regime; it is not astronomical daylight.'});
for(const [crop,t] of [['MAIZE',37.9],['RICE',37.2],['WHEAT',27.3]])define(crop+'_HEAT_DAY'+String(t).replace('.','_'),'Daytime mean 2 m air temperature','Tday = mean hourly T2m during 06:00–18:00 local solar clock; Tday > '+t+' C.',t,'>',1,{profile:'day_mean',duration_basis:unspecified,note:'Daytime mean is the explicit project mapping of heterogeneous controlled daytime treatments in the synthesis; daily maximum is not substituted.'});
for(const [crop,t,n] of [['MAIZE',27.3,1],['RICE',31.2,8],['WHEAT',19.6,8]])define(crop+'_HEAT_NIGHT'+String(t).replace('.','_'),'Nighttime mean 2 m air temperature','Tnight = mean hourly T2m during 18:00–06:00 local solar clock; Tnight '+(crop==='MAIZE'?'>=':'>')+' '+t+' C.',t,crop==='MAIZE'?'>=':'>',n,{profile:'night_mean',duration_basis:crop==='MAIZE'?unspecified:'The reviewed synthesis says more than one week: >=8 complete nights. Original workbook seven-day value is retained as source metadata, with this correction explicit.',note:'Fixed local solar-clock night is an operational mapping. The approximate maize estimate is operationalized as >=27.3 C; uncertainty remains in the paper, not a precise universal boundary.'});
define('MAIZE_HEAT_FILL39_4_41_5','Six-day mean of daily maximum 2 m air temperature','mean(Tmax[d-5:d]) >=39.4 C. Duration is the union of qualifying complete six-day windows.',39.4,'>=',6,{band:'temperature_2m_max',mode:'rolling_mean'});
define('MAIZE_HNT_FILL28_18D','Daily minimum 2 m air temperature','Tmin >=28 C for 18 consecutive complete UTC days.',28,'>=',18,{band:'temperature_2m_min',evidence_update:'Wang et al. 2026, sections 2.2–2.3: treatments were daily minima 24/26/28/30 C, minimum around 05:00–06:00; heating lasted 18 days.',note:'Daily minimum reproduces the treatment-defining quantity rather than an unspecified nighttime mean. UTC daily grouping is a reanalysis transfer from the local chamber cycle.'});
define('MAIZE_R6_WIND15','Hourly 10 m wind-speed magnitude','U10 = sqrt(u10^2 + v10^2), computed before spatial reduction; U10 >15 m/s.',15,'>',1,{band:'wind_speed_10m',resolution:'hour',unit:'m/s',conversion:'identity',duration_basis:unspecified,note:'10 m wind is a meteorological screening proxy for wind-tunnel loading. It is not a gust or a calibrated stalk-breaking probability; height and canopy transfer remain limitations.'});
define('RICE_GERMINATION_HEAT38_24H','Hourly 2 m air temperature','Tair >=38 C for 24 consecutive hourly samples.',38,'>=',24,{resolution:'hour'});
for(const [id,t,op,n] of [['RICE_HEAT_MEAN_33',33,'>=',1],['RICE_COLD_ANTHESIS17_5D',17,'<=',5],['RICE_COLD_MEAN20',20,'<=',1],['RICE_COLD_MEAN17',17,'<=',1],['RICE_RIPENING_HEAT_MEAN28',28,'>',1]])define(id,'Daily mean 2 m air temperature','Tmean = daily mean temperature_2m - 273.15; Tmean '+op+' '+t+' C.',t,op,n,{duration_basis:id.includes('RIPENING')?unspecified:'Reviewed daily exposure duration; not maximum plant tolerance'});
define('RICE_RAIN25','Daily accumulated precipitation','Pday = total_precipitation_sum * 1000; Pday >=25 mm/day.',25,'>=',1,{band:'total_precipitation_sum',unit:'mm/day',conversion:'metres_to_mm'});
define('RICE_DROUGHT_SM75','Estimated relative surface soil moisture (field-capacity reference)','SMrel = 100 * (0.7*theta_0_7cm + 0.3*theta_7_28cm) / theta_FC; theta_FC = mean(OpenLandMap 33 kPa b0,b10)/100.',75,'<=',10,{band:'relative_soil_moisture',unit:'% of field capacity',conversion:'identity',equivalence:'Model-derived proxy; denominator explicitly chosen by the project',note:'Sun et al. uses 0–10 cm relative soil moisture. Field capacity at 33 kPa is the declared operational denominator here, not a denominator verified in the paper. Combining ERA5 and OpenLandMap requires local validation. It is not a soil-moisture percentile.',evidence_update:'Sun et al. 2025 section 2.2 and Table 1; OpenLandMap field-capacity catalogue DOI 10.5281/zenodo.2629589.'});
define('SOY_SEASONAL_HEAT30','Accumulated hourly temperature exposure above 30 C','E = sum(hours with Tair >30 C); E/24 gives equivalent exposure days. Default event: E >=24 hours within the phase; hours need not be consecutive.',30,'>',24,{resolution:'hour',mode:'accumulated',duration_basis:'Project event cutoff of one accumulated equivalent exposure day; not a published minimum damaging duration.',note:'Schauberger et al. aggregates fractional exposure days across a fixed growing season using sinusoidal interpolation of daily extrema. Here actual hourly reanalysis samples are accumulated within the selected estimated phase. This preserves accumulated rather than consecutive exposure, but changes temporal source and seasonal scope; no phase-specific yield coefficient is inferred.',evidence_update:'Nature Communications 10.1038/ncomms13931, Methods: temperature-bin exposure days across a fixed growing season.'});
define('SOY_HNT_FILL28_R5_R7','Minimum temperature during a complete 12-hour night','min(Tair[18:00–06:00]) >=28 C; every hourly sample in the fixed 12-hour night must qualify.',28,'>=',1,{profile:'night_min',duration_basis:'One complete 12-hour experimental-style night. Repetition across nights is an analysis setting, not a published minimum damaging count.'});
define('WHEAT_SEEDLING_HEAT42','Hourly 2 m air temperature','Tair >=42 C for 24 consecutive hourly samples.',42,'>=',24,{resolution:'hour',note:'The paper reports a 42 C treatment. The >= comparator is the project exposure rule, not a measured dose-response breakpoint. Source remains secondary.'});
define('WHEAT_BOOT_COLD_MINUS2_24H','Hourly 2 m air temperature','Tair <=-2 C for 24 consecutive hourly samples.',-2,'<=',24,{resolution:'hour'});
define('WHEAT_BOOT_HEAT35_30_24H','Paired 16-hour daytime and 8-hour nighttime mean temperature','Tday = mean(06:00–22:00); Tnight = mean(22:00–06:00); paired means >=35/30 C in one complete 24-hour cycle.',35,'>=',1,{profile:'paired_mean',secondary_threshold:30,day_hours:16,night_start:22,evidence_update:'Barber et al. 2017 methods: 24 h treatment, 16 h day, night 22:00–06:00; reviewed workbook row 58.'});
define('WHEAT_RIPENING_RAIN5_8H','Hourly accumulated precipitation','Phour = total_precipitation_hourly * 1000; Phour >=5 mm/hour for 8 consecutive hours. Source timestamp is hour-end.',5,'>=',8,{band:'total_precipitation_hourly',resolution:'hour',unit:'mm/hour',conversion:'metres_to_mm'});
function external(id,variable,equation,t,op,n,unit,csv_variable,note,opts={}){define(id,variable,equation,t,op,n,{access:'import',band:csv_variable,csv_variable,unit,conversion:'identity',note,...opts});}
external('MAIZE_EARLYVEG_DROUGHT_SWP051_4D','Daily mean soil matric potential','psi_MPa = psi_kPa / 1000; psi_MPa <= -0.51 MPa for 4 days.',-.51,'<=',4,'MPa','soil_matric_potential_mpa','Requires measured/modelled matric potential at a documented root-zone depth. A retention-model conversion must carry its soil-specific parameters; ERA5 volumetric moisture alone cannot determine it.');
external('RICE_DROUGHT_FLOWERING_SWP30','Daily mean soil matric potential','psi_kPa <= -30 kPa. Default one-day exposure is an analysis setting.',-30,'<=',1,'kPa','soil_matric_potential_kpa','Supply soil potential, not volumetric moisture. Experimental -30 +/-5 kPa treatment does not establish a damage-onset duration.',{duration_basis:unspecified});
external('RICE_SUBMERGENCE_SENSITIVE7D','Daily complete-crop-submergence indicator','I = 1 when water surface is above the crop canopy for the complete day; run(I=1) >=7 days.',1,'>=',7,'0/1','complete_submergence','Requires daily complete-submergence observations or a water-depth/canopy-height model. Sensitive-variety condition is retained. Monthly water or rainfall is not equivalent.');
external('SOY_FLOOD_DURATION3','Daily continuous flooding indicator','I = 1 for a complete flooded day; run(I=1) >3 days, hence >=4 complete daily intervals.',1,'>=',4,'0/1','flooded','The strict >3-day condition is retained; it is not silently changed to three days.');
external('SOY_FLOOD_DURATION6_GRAIN','Daily continuous flooding indicator','I = 1 for a complete flooded day; run(I=1) >6 days, hence >=7 complete daily intervals.',1,'>=',7,'0/1','flooded','The strict >6-day condition is retained. Supply daily hydrology; rainfall is not flooding.');
external('SOY_WATERLOG_R1_3CM_16D','Daily minimum standing-water depth above soil','h_min >=3 cm for 16 consecutive days.',3,'>=',16,'cm','standing_water_depth_cm','Minimum daily depth preserves continuous inundation; daily mean depth alone does not establish the treatment.');
external('WHEAT_STEM_DROUGHT_VSMC45_14D','Volumetric soil-moisture reduction relative to a matched control','R = 100*(1-theta_treatment/theta_control); R >=45% for 14 consecutive days.',45,'>=',14,'% reduction','soil_moisture_reduction_percent','Supply matched control and treatment data through this derived variable and document the control in provenance. A climatological anomaly is a different experiment.');
external('WHEAT_FROST_POSTHEADING_CANOPY_MINUS3_5','Minimum air temperature within the crop canopy','Tcanopy_min <=-3.5 C; one daily minimum by default.',-3.5,'<=',1,'C','canopy_temperature_min_c','Requires canopy temperature or a validated station-to-canopy model. 2 m temperature without that model is not an exact equivalent.',{duration_basis:unspecified});
external('WHEAT_WATERLOG_Z65_3D','Daily complete root-zone-waterlogging indicator','I = 1 for a complete waterlogged day; run(I=1) >=3 days.',1,'>=',3,'0/1','waterlogged','Daily hydrology or root-zone oxygen/water-table model required. This is a treatment indicator, not a demonstrated three-day yield-loss onset.');
external('WHEAT_HNT_POSTANTHESIS_DELTA3_8','Nighttime mean air-temperature difference against a matched control','DeltaTnight = mean(Tnight_treatment)-mean(Tnight_control) >=3.8 C.',3.8,'>=',1,'C difference','night_temperature_difference_c','The source applies warming every night across the treatment period. One night is an analysis duration, not the duration of the experiment. A climate-normal anomaly is not the experimental counterfactual.',{duration_basis:unspecified});
for(const rule of audit.rules){const d=definitions[rule.rule_id];if(!d)throw Error('Missing exact equivalence '+rule.rule_id);rule.equivalence=d;rule.spec=d.spec;rule.status=d.access==='gee'?'operational':'external';rule.reason=d.note;}
audit.version='regional-v4-2026-09-16';audit.interpretation='Every retained rule has an explicit measurement and event definition. GEE transfers and project proxies are distinguished from exact external measurements. No universal maximum plant tolerance is inferred.';
const definitionPath='scripts/build_variable_equivalences.mjs';
audit.inputs=audit.inputs.filter(i=>i.path!==definitionPath);
audit.inputs.push({path:definitionPath,sha256:createHash('sha256').update(fs.readFileSync(path.join(root,definitionPath))).digest('hex')});
audit.datasets=[daily,hourly,'OpenLandMap/SOL/SOL_WATERCONTENT-33KPA_USDA-4B1C_M/v01'];
fs.writeFileSync(file,JSON.stringify(audit,null,2)+'\n');
fs.writeFileSync(path.join(root,'docs/variable_equivalences_v4.md'),'# Explicit variable equivalences\n\nPaper values and source assignments are preserved in the JSON registry. The operational equation is a project definition and does not establish universal plant tolerance. The original Excel is unchanged.\n\n| Rule | Exact analysis variable | Equation | Access | Qualification |\n|---|---|---|---|---|\n'+audit.rules.map(r=>`| ${r.rule_id} | ${r.equivalence.variable} | ${r.equivalence.equation} | ${r.equivalence.access} | ${r.equivalence.note} ${r.equivalence.duration_basis} |`).join('\n')+'\n');
console.log('Explicit equations:',audit.rules.length,'GEE:',audit.rules.filter(r=>r.status==='operational').length,'Exact external series:',audit.rules.filter(r=>r.status==='external').length);
