const assert = require('node:assert/strict');
const ts = require('typescript');
const fs = require('node:fs');
const path = require('node:path');
const code = ts.transpileModule(fs.readFileSync(path.join(__dirname, '../lib/atlas.ts'), 'utf8'), {compilerOptions: {module: ts.ModuleKind.CommonJS}}).outputText;
const exported = {};
new Function('exports', code)(exported);
const {summarizeCell, frequencyBin, withinBounds} = exported;
const row = {cell: '1.25,2.25', phase: 'EST', years: [{year: 2000, event: true}, {year: 2001, event: false}, {year: 2002, event: null, error: 'Unavailable'}]};
assert.deepEqual(summarizeCell(row, 3), {valid: 2, events: 1, completed: 3, partial: false, probability: .5});
assert.equal(summarizeCell(undefined, 35).probability, null);
assert.equal(summarizeCell({...row, years: [{year: 2000, event: false}]}, 1).probability, 0);
assert.equal(summarizeCell(row, 35).partial, true);
assert.deepEqual([0, .001, .2, .201, .4, .6, .8, 1].map(frequencyBin), [0, 1, 1, 2, 2, 3, 4, 5]);
assert.equal(withinBounds('1.25,179.25', [170, -10, 190, 10]), true);
assert.equal(withinBounds('1.25,-179.25', [170, -10, 190, 10]), true);
assert.equal(withinBounds('1.25,0.25', [170, -10, 190, 10]), false);
assert.equal(withinBounds('20.25,179.25', [170, -10, 190, 10]), false);
console.log('Atlas: denominator, zero vs missing, partial coverage, bin boundaries and dateline checks passed.');
